// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	MMenu        string
	MMusclepart  string
	MUser        string
	TBodycomp    string
	TTraininglog string
}{
	MMenu:        "m_menu",
	MMusclepart:  "m_musclepart",
	MUser:        "m_user",
	TBodycomp:    "t_bodycomp",
	TTraininglog: "t_traininglog",
}
